### ISSUE TITLE
замечания 

### ISSUE THREAD

**Issue by demist** [enscogitans/tp#1]
+ нет схемы архитектуры
+ не должно быть чего-то в стиле `std::cout << "\tSome information about Aztec tank destroyer.\n";
}`
Все подобные ресурсы должны храниться отдельно, иначе как потом, например, делать локализацию?

плюсы:
+ разбивка проекта на разные файлы
+ константы вынесены (но лучше, если будет вообще отдельный файл конфигов/ресурсов)

**Comment by enscogitans** [comment]
Метод getInfo() будет в будущем удалён. На данный момент он нужен лишь для демонстрации возможностей программы

**Comment by demist** [comment]
ок, засчитано
